services:
  - type: web
    name: web-scraper-dashboard
    runtime: python
    repo: https://github.com/yourusername/web_scraper_dashboard
    plan: free
    region: oregon
    buildCommand: bash build.sh
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://sakshi_db_user:KUwt9KQgBxxfgQLx@cluster7.euszxtv.mongodb.net/
      - key: DATABASE_NAME
        value: scraper_dashboard
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
