services:
  - type: web
    name: web-scraper-dashboard
    runtime: python
    repo: https://github.com/yourusername/web_scraper_dashboard
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng chromium-driver chromium
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://sakshi_db_user:KUwt9KQgBxxfgQLx@cluster7.euszxtv.mongodb.net/
      - key: DATABASE_NAME
        value: scraper_dashboard
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: PYTHONUNBUFFERED
        value: "1"
